### PR TITLE
Enable and/or searching

### PR DESCRIPTION
**Pull request by Jain-Aditya**
Phabricator Task: https://phabricator.wikimedia.org/T216398

### CODE REVIEW

**Comment by Jain-Aditya** [comment]
Hi @Samwalton9, I am opening a new PR with the same changes that you suggested in the previous one.
Actually I was trying to handle some merge conflicts in the old PR and really did something bad So I closed it. Sorry for the inconvenience caused. Review it whenever you have time. Thanks.

**Comment by Jain-Aditya** [comment]
@Samwalton9 It would be great if you could review this. :)

**Comment by Jain-Aditya** [comment]
@Samwalton9 Just a gentle reminder to review this. :) 

Also, Shall I add a test for this functionality?

**Comment by Samwalton9** [comment]
Merged to https://github.com/WikipediaLibrary/hashtags/pull/38

**Pull request closed without merging**
