### PR TITLE
Added Feature for Support of Code Coverage

### PR DESCRIPTION
**Pull request by ParthS007**
Phab Task link: https://phabricator.wikimedia.org/T216614
Added Feature for Support of Code Coverage
@Samwalton9 Please review. Thanks

### CODE REVIEW

**Comment by Samwalton9** [comment]
Looks like this build is failing, could you check if more work needs to be done here?
```
manage.py test: error: unrecognized arguments: --coverage-clover=coverage.xml
The command "docker exec hashtags_app_1 python manage.py test --coverage-clover=coverage.xml" exited with 2.
```

**Comment by ParthS007** [comment]
@Samwalton9 I am working on this and finding a workaround for this. I will update the PR asap. :+1: 
Thanks for the review :)

**Comment by FirePing32** [comment]
https://github.com/Samwalton9/hashtags/blob/06de72fbb9a689ff90e0caf295465159daef53e8/.travis.yml#L12
I think you have to initialize a environment first for codecov to work.
Try replacing this line with this -
```bash
- bash <(curl -s https://codecov.io/env)
```
Don't change the ``after_script`` code.

**Comment by ParthS007** [comment]
@Samwalton9 Codecov is finally integrated. Please review it. Thanks

**Comment by Samwalton9** [comment]
This looks great, thank you!

**Pull request merged**
