### PR TITLE
[WIP] Add elasticsearch

### PR DESCRIPTION
**Pull request by Samwalton9**
Until now this has been a search tool with no search engine. It's time we fixed that.

Work in progress.

### CODE REVIEW

**Comment by Samwalton9** [comment]
- Elasticsearch added, sets up Docker container correctly.
 - Basic search works, but uses the `q` parameter instead of `query`, which is what we used before. I've struggled to find a way to change this, and _really_ don't want to break everyone's links if we can help it. Ideally we'd update this so it uses `query` again. This means if you want to test this branch clicking Search currently doesn't work, you need to modify the URL to use `?q=` instead.
    - Maybe we should just redirect `query` to `q`.
 - Top-level statistics don't currently work. Django-haystack uses modified Querysets that don't do all the things we want them to do. In particular it can't do `.values().distinct()`. Need to see if there's a better way to do this. We also need to double check what it's doing with duplicate entries right now. In the base tool we use some convoluted `values_list`s to filter duplicate edits, but that code isn't touched by haystack right now.

If you pull this branch to work on it, right now you need to manually build the elasticsearch index with `docker exec -it hashtags_app_1 python manage.py rebuild_index` each time you want to update your data. In production we'll have a cron job doing this on a regular basis.

**Comment by FirePing32** [comment]
I had earlier tested some elastic-search based apps which returned results on proper configuration on larger databases.
I am finding the best configuration for this.

**Comment by FirePing32** [comment]
https://github.com/Samwalton9/hashtags/blob/2083a0d114c516a18a9f0c24ebbbf892f37905ff/docker-compose.yml#L29
https://github.com/Samwalton9/hashtags/blob/2083a0d114c516a18a9f0c24ebbbf892f37905ff/requirements/django_app.txt#L3
@Samwalton9 There is a difference in the version number of ``elasticsearch``. It maybe that this difference is not leting the app build correctly.

**Comment by Samwalton9** [comment]
Welp, was planning to rebase onto master but accidentally did a full merge and this commit is now a mess. Will fix.

**Pull request closed without merging**
