### PR TITLE
Add paginator bar to full list of users

### PR DESCRIPTION
**Pull request by Jain-Aditya**
Phabricator task: [T227319](https://phabricator.wikimedia.org/T227319)

### CODE REVIEW

**Comment by Jain-Aditya** [comment]
Pulled the changes into staging tool.
https://hashtags-staging.wmflabs.org/all_users/?query=1lib1ref&enddate=2019-06-05&startdate=2019-05-15&project=

**Comment by Samwalton9** [comment]
Looks good except that I think `>>` is usually used to signify the last page, not the next one. Maybe just a single >, or actually writing `Next` would be better, whichever you prefer!

**Comment by Jain-Aditya** [comment]
I think, writing Next and Previous would be better.

**Comment by Samwalton9** [comment]
Looks good!

**Pull request merged**
