### PR TITLE
Resize buttons on results page

### PR DESCRIPTION
**Pull request by sanyam-git**
with reference to [T242130](https://phabricator.wikimedia.org/T242130)
added a new class for both-buttons.

### CODE REVIEW

**Comment by Samwalton9** [comment]
Thanks for this pull request! It would be helpful if you could attach a screenshot to show the result of this change :)

**Comment by sanyam-git** [comment]
Sure :)
Screenshot from 2020-01-23 16-01-09

**Comment by Jain-Aditya** [comment]
Thanks for this PR! I have tested it locally and the buttons now look too large.
image
I think - they should be of the same size as the previous `Show statistics` button. What do you say @Samwalton9 ?

**Comment by Samwalton9** [comment]
Personally I think they look fine :) If all looks good to you Aditya, you can go ahead and merge!

**Comment by Jain-Aditya** [comment]
Ok, thanks for the clarification Sam! Going ahead and merging.

**Comment by sanyam-git** [comment]
Thanks, @Jain-Aditya and @Samwalton9. It was a small PR, but first one for me. Looking forward to contribute more.

**Pull request merged**
